export const PROJECT_AGENT_SOURCE_GITHUB_MAX_TREE_ENTRIES = 500;
export const PROJECT_AGENT_SOURCE_GITHUB_MAX_INCLUDED_FILES = 40;
export const PROJECT_AGENT_SOURCE_GITHUB_FILE_MAX_BYTES = 512 * 1024;
export const PROJECT_AGENT_SOURCE_GITHUB_TOTAL_FETCHED_BYTES = 5 * 1024 * 1024;
export const PROJECT_AGENT_SOURCE_GITHUB_TOTAL_TEXT_MAX_LENGTH = 80000;
export const PROJECT_AGENT_SOURCE_GITHUB_TIMEOUT_MS = 10000;
