-- Current Supabase schema snapshot for the portfolio.
-- Migration files under database/migrations/ are the ordered setup history.

-- =========================
-- ABOUT
-- =========================
CREATE TABLE IF NOT EXISTS about (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_image       TEXT,
    profession_title    TEXT NOT NULL DEFAULT '',
    brief_bio           TEXT,
    resume_pdf          TEXT
);

COMMENT ON TABLE about IS
    'Singleton profile/about content. The local admin backend upserts id = 1.';

-- =========================
-- PROJECTS
-- =========================
CREATE TABLE IF NOT EXISTS project_section (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    about_projects      TEXT
);

COMMENT ON TABLE project_section IS
    'Singleton project section intro content. The local admin backend upserts id = 1.';

CREATE TABLE IF NOT EXISTS projects (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permalink               TEXT,

    image_url               TEXT,
    video_url               TEXT,
    architecture_image_url  TEXT,

    title                   TEXT NOT NULL DEFAULT '',
    card_description        TEXT,
    live_url                TEXT,

    overview                TEXT,
    role                    TEXT,
    source_url              TEXT,
    writeup_url             TEXT,
    video_page_url          TEXT,

    tech_stack              JSONB,
    tech_tags               JSONB,
    features                JSONB,
    metrics                 JSONB,
    challenges              JSONB,
    improvements            JSONB,

    featured_rank           INTEGER,
    project_type            TEXT,
    labels                  JSONB,

    published               BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order              INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT projects_project_type_check
        CHECK (
            project_type IS NULL
            OR project_type IN ('school', 'internship', 'competition', 'personal', 'client', 'open-source')
        ),
    CONSTRAINT projects_labels_array_check
        CHECK (labels IS NULL OR jsonb_typeof(labels) = 'array')
);

COMMENT ON TABLE projects IS
    'Project cards and modal details used by the public site and local admin backend.';

COMMENT ON COLUMN projects.permalink IS
    'Stable human-readable route segment generated by the local admin backend.';
COMMENT ON COLUMN projects.tech_stack IS
    'JSON object with frontend, backend, data, and infrastructure arrays.';
COMMENT ON COLUMN projects.tech_tags IS
    'JSON string array used for project card tags.';
COMMENT ON COLUMN projects.features IS
    'JSON string array for modal feature bullets.';
COMMENT ON COLUMN projects.metrics IS
    'Nullable JSON string array for modal metrics.';
COMMENT ON COLUMN projects.challenges IS
    'Nullable JSON array of objects with challenge, solution, and result fields.';
COMMENT ON COLUMN projects.improvements IS
    'JSON string array for modal future improvements.';
COMMENT ON COLUMN projects.featured_rank IS
    'Nullable integer for featured project ordering. Null means not featured; lower numbers sort first.';
COMMENT ON COLUMN projects.project_type IS
    'Optional primary project classification: school, internship, competition, personal, client, or open-source.';
COMMENT ON COLUMN projects.labels IS
    'Optional JSONB string array of display labels for project cards and details.';

CREATE INDEX IF NOT EXISTS projects_public_order_idx
    ON projects (published, sort_order, id);

CREATE UNIQUE INDEX IF NOT EXISTS projects_permalink_unique_idx
    ON projects (permalink)
    WHERE permalink IS NOT NULL AND btrim(permalink) <> '';

-- =========================
-- SKILLS
-- =========================
CREATE TABLE IF NOT EXISTS skills (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_label         TEXT NOT NULL DEFAULT '',
    label               TEXT NOT NULL DEFAULT '',
    group_sort_order    INTEGER NOT NULL DEFAULT 0,
    item_sort_order     INTEGER NOT NULL DEFAULT 0,
    published           BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE skills IS
    'Grouped Skills rows used by the public portfolio and local admin backend.';
COMMENT ON COLUMN skills.group_label IS
    'Display group for a skill item, such as Core Web Stack or Backend.';
COMMENT ON COLUMN skills.label IS
    'Skill item text shown inside its group.';
COMMENT ON COLUMN skills.group_sort_order IS
    'Stable ordering for skill groups.';
COMMENT ON COLUMN skills.item_sort_order IS
    'Stable ordering for skill items within a group.';
COMMENT ON COLUMN skills.published IS
    'Whether the grouped skill row is available to public Skills reads.';

CREATE INDEX IF NOT EXISTS skills_public_grouped_order_idx
    ON skills (published, group_sort_order, group_label, item_sort_order, label, id);

-- =========================
-- CREDENTIALS
-- =========================
CREATE TABLE IF NOT EXISTS credentials (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_kind     TEXT NOT NULL,
    title               TEXT NOT NULL DEFAULT '',
    organization        TEXT NOT NULL DEFAULT '',
    credential_type     TEXT,
    description         TEXT,
    highlights          JSONB,
    issued_label        TEXT,
    gpa                 TEXT,
    credential_url      TEXT,
    logo_url            TEXT,
    logo_key            TEXT,
    logo_scale          NUMERIC,
    published           BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order          INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT credentials_kind_check
        CHECK (credential_kind IN ('education', 'certification')),
    CONSTRAINT credentials_highlights_array_check
        CHECK (highlights IS NULL OR jsonb_typeof(highlights) = 'array')
);

COMMENT ON TABLE credentials IS
    'Education and Certification cards used by the public portfolio and local admin backend.';
COMMENT ON COLUMN credentials.credential_kind IS
    'Credential section discriminator: education or certification.';
COMMENT ON COLUMN credentials.title IS
    'Display title, such as B.S. in Computer Science or Azure Fundamentals.';
COMMENT ON COLUMN credentials.organization IS
    'Display issuer or school, such as Washington State University or Microsoft.';
COMMENT ON COLUMN credentials.credential_type IS
    'Display type, such as Bachelor''s Degree, Minor, Certification, or Certificate.';
COMMENT ON COLUMN credentials.description IS
    'Credential card body copy.';
COMMENT ON COLUMN credentials.highlights IS
    'JSON string array for credential highlight chips.';
COMMENT ON COLUMN credentials.issued_label IS
    'Display issue date, range, or expected-completion label.';
COMMENT ON COLUMN credentials.gpa IS
    'Optional display GPA, intended for education rows.';
COMMENT ON COLUMN credentials.credential_url IS
    'Optional official program, certificate, or credential URL.';
COMMENT ON COLUMN credentials.logo_url IS
    'Optional public image URL that wins over logo_key in UI-facing code.';
COMMENT ON COLUMN credentials.logo_key IS
    'Optional bundled logo key resolved by UI-facing code, such as wsu, edcc, or microsoft.';
COMMENT ON COLUMN credentials.logo_scale IS
    'Optional card logo scale; admin validation clamps this to the supported display range.';
COMMENT ON COLUMN credentials.published IS
    'Whether the credential row is available to public reads.';
COMMENT ON COLUMN credentials.sort_order IS
    'Stable ordering inside each credential_kind.';

CREATE INDEX IF NOT EXISTS credentials_public_order_idx
    ON credentials (published, credential_kind, sort_order, id);

-- =========================
-- CONTACT
-- =========================
CREATE TABLE IF NOT EXISTS links (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label               TEXT NOT NULL,
    url                 TEXT NOT NULL,
    svg                 TEXT
);

COMMENT ON TABLE links IS
    'Contact and social links with optional uploaded icon URL in svg.';
