-- Current Supabase schema snapshot for the portfolio.
-- Migration files under database/migrations/ are the ordered setup history.

-- =========================
-- ABOUT
-- =========================
CREATE TABLE IF NOT EXISTS about (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_image       TEXT,
    profession_title    TEXT NOT NULL DEFAULT '',
    brief_bio           TEXT,
    resume_pdf          TEXT
);

COMMENT ON TABLE about IS
    'Singleton profile/about content. The local admin backend upserts id = 1.';

-- =========================
-- PROJECTS
-- =========================
CREATE TABLE IF NOT EXISTS project_section (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    about_projects      TEXT
);

COMMENT ON TABLE project_section IS
    'Singleton project section intro content. The local admin backend upserts id = 1.';

CREATE TABLE IF NOT EXISTS projects (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permalink               TEXT,

    image_url               TEXT,
    video_url               TEXT,
    architecture_image_url  TEXT,

    title                   TEXT NOT NULL DEFAULT '',
    card_description        TEXT,
    live_url                TEXT,

    overview                TEXT,
    role                    TEXT,
    source_url              TEXT,
    writeup_url             TEXT,
    video_page_url          TEXT,

    tech_stack              JSONB,
    tech_tags               JSONB,
    features                JSONB,
    metrics                 JSONB,
    challenges              JSONB,
    improvements            JSONB,

    published               BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order              INTEGER NOT NULL DEFAULT 0
);

COMMENT ON TABLE projects IS
    'Project cards and modal details used by the public site and local admin backend.';

COMMENT ON COLUMN projects.permalink IS
    'Stable human-readable route segment generated by the local admin backend.';
COMMENT ON COLUMN projects.tech_stack IS
    'JSON object with frontend, backend, data, and infrastructure arrays.';
COMMENT ON COLUMN projects.tech_tags IS
    'JSON string array used for project card tags.';
COMMENT ON COLUMN projects.features IS
    'JSON string array for modal feature bullets.';
COMMENT ON COLUMN projects.metrics IS
    'Nullable JSON string array for modal metrics.';
COMMENT ON COLUMN projects.challenges IS
    'Nullable JSON array of objects with challenge, solution, and result fields.';
COMMENT ON COLUMN projects.improvements IS
    'JSON string array for modal future improvements.';

CREATE INDEX IF NOT EXISTS projects_public_order_idx
    ON projects (published, sort_order, id);

CREATE UNIQUE INDEX IF NOT EXISTS projects_permalink_unique_idx
    ON projects (permalink)
    WHERE permalink IS NOT NULL AND btrim(permalink) <> '';

-- =========================
-- SKILLS
-- =========================
CREATE TABLE IF NOT EXISTS skills (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_label         TEXT NOT NULL DEFAULT '',
    label               TEXT NOT NULL DEFAULT '',
    group_sort_order    INTEGER NOT NULL DEFAULT 0,
    item_sort_order     INTEGER NOT NULL DEFAULT 0,
    published           BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE skills IS
    'Grouped Skills rows used by the public portfolio and local admin backend.';
COMMENT ON COLUMN skills.group_label IS
    'Display group for a skill item, such as Core Web Stack or Backend.';
COMMENT ON COLUMN skills.label IS
    'Skill item text shown inside its group.';
COMMENT ON COLUMN skills.group_sort_order IS
    'Stable ordering for skill groups.';
COMMENT ON COLUMN skills.item_sort_order IS
    'Stable ordering for skill items within a group.';
COMMENT ON COLUMN skills.published IS
    'Whether the grouped skill row is available to public Skills reads.';

CREATE INDEX IF NOT EXISTS skills_public_grouped_order_idx
    ON skills (published, group_sort_order, group_label, item_sort_order, label, id);

-- =========================
-- CONTACT
-- =========================
CREATE TABLE IF NOT EXISTS links (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label               TEXT NOT NULL,
    url                 TEXT NOT NULL,
    svg                 TEXT
);

COMMENT ON TABLE links IS
    'Contact and social links with optional uploaded icon URL in svg.';
