-- Migration 0001: current portfolio schema.
--
-- This migration is intentionally non-destructive. It creates the current
-- runtime tables when missing and adds columns expected by the app when a table
-- already exists. Review live data before adding stricter constraints manually.

-- =========================
-- ABOUT
-- =========================
CREATE TABLE IF NOT EXISTS about (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_image       TEXT,
    profession_title    TEXT NOT NULL DEFAULT '',
    brief_bio           TEXT,
    resume_pdf          TEXT
);

ALTER TABLE about ADD COLUMN IF NOT EXISTS profile_image TEXT;
ALTER TABLE about ADD COLUMN IF NOT EXISTS profession_title TEXT;
ALTER TABLE about ADD COLUMN IF NOT EXISTS brief_bio TEXT;
ALTER TABLE about ADD COLUMN IF NOT EXISTS resume_pdf TEXT;

UPDATE about
SET profession_title = ''
WHERE profession_title IS NULL;

ALTER TABLE about ALTER COLUMN profession_title SET DEFAULT '';
ALTER TABLE about ALTER COLUMN profession_title SET NOT NULL;

COMMENT ON TABLE about IS
    'Singleton profile/about content. The local admin backend upserts id = 1.';

-- =========================
-- PROJECTS
-- =========================
CREATE TABLE IF NOT EXISTS project_section (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    about_projects      TEXT
);

ALTER TABLE project_section ADD COLUMN IF NOT EXISTS about_projects TEXT;

COMMENT ON TABLE project_section IS
    'Singleton project section intro content. The local admin backend upserts id = 1.';

CREATE TABLE IF NOT EXISTS projects (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permalink               TEXT,
    image_url               TEXT,
    video_url               TEXT,
    architecture_image_url  TEXT,
    title                   TEXT NOT NULL DEFAULT '',
    card_description        TEXT,
    live_url                TEXT,
    overview                TEXT,
    role                    TEXT,
    source_url              TEXT,
    writeup_url             TEXT,
    video_page_url          TEXT,
    tech_stack              JSONB,
    tech_tags               JSONB,
    features                JSONB,
    metrics                 JSONB,
    challenges              JSONB,
    improvements            JSONB,
    published               BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order              INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS permalink TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS architecture_image_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS card_description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS live_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS overview TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS writeup_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS video_page_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tech_stack JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tech_tags JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS features JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS metrics JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS challenges JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS improvements JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS published BOOLEAN;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS sort_order INTEGER;

UPDATE projects
SET
    title = COALESCE(title, ''),
    published = COALESCE(published, TRUE),
    sort_order = COALESCE(sort_order, 0);

ALTER TABLE projects ALTER COLUMN title SET DEFAULT '';
ALTER TABLE projects ALTER COLUMN title SET NOT NULL;
ALTER TABLE projects ALTER COLUMN published SET DEFAULT TRUE;
ALTER TABLE projects ALTER COLUMN published SET NOT NULL;
ALTER TABLE projects ALTER COLUMN sort_order SET DEFAULT 0;
ALTER TABLE projects ALTER COLUMN sort_order SET NOT NULL;

COMMENT ON TABLE projects IS
    'Project cards and modal details used by the public site and local admin backend.';
COMMENT ON COLUMN projects.permalink IS
    'Stable human-readable route segment generated by the local admin backend.';
COMMENT ON COLUMN projects.tech_stack IS
    'JSON object with frontend, backend, data, and infrastructure arrays.';
COMMENT ON COLUMN projects.tech_tags IS
    'JSON string array used for project card tags.';
COMMENT ON COLUMN projects.features IS
    'JSON string array for modal feature bullets.';
COMMENT ON COLUMN projects.metrics IS
    'Nullable JSON string array for modal metrics.';
COMMENT ON COLUMN projects.challenges IS
    'Nullable JSON array of objects with challenge, solution, and result fields.';
COMMENT ON COLUMN projects.improvements IS
    'JSON string array for modal future improvements.';

CREATE INDEX IF NOT EXISTS projects_public_order_idx
    ON projects (published, sort_order, id);

-- If this fails on an existing database, backfill or dedupe permalinks first.
CREATE UNIQUE INDEX IF NOT EXISTS projects_permalink_unique_idx
    ON projects (permalink)
    WHERE permalink IS NOT NULL AND btrim(permalink) <> '';

-- =========================
-- CONTACT
-- =========================
CREATE TABLE IF NOT EXISTS skills (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT NOT NULL,
    level               TEXT NOT NULL
);

ALTER TABLE skills ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS level TEXT;

UPDATE skills
SET
    name = COALESCE(name, ''),
    level = COALESCE(level, 'experiencing');

ALTER TABLE skills ALTER COLUMN name SET NOT NULL;
ALTER TABLE skills ALTER COLUMN level SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'skills_level_check'
          AND conrelid = 'skills'::regclass
    ) THEN
        ALTER TABLE skills
            ADD CONSTRAINT skills_level_check
            CHECK (level IN ('proficient', 'experiencing'))
            NOT VALID;
    END IF;
END $$;

COMMENT ON TABLE skills IS
    'Contact skill rows. Public mappers group rows by level.';

CREATE TABLE IF NOT EXISTS links (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label               TEXT NOT NULL,
    url                 TEXT NOT NULL,
    svg                 TEXT
);

ALTER TABLE links ADD COLUMN IF NOT EXISTS label TEXT;
ALTER TABLE links ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE links ADD COLUMN IF NOT EXISTS svg TEXT;

UPDATE links
SET
    label = COALESCE(label, ''),
    url = COALESCE(url, '');

ALTER TABLE links ALTER COLUMN label SET NOT NULL;
ALTER TABLE links ALTER COLUMN url SET NOT NULL;

COMMENT ON TABLE links IS
    'Contact and social links with optional uploaded icon URL in svg.';
