-- Migration 0002: public read policies and storage bucket setup.
--
-- The public portfolio uses the anon key for reads. The local admin backend
-- uses the service role key for privileged writes and storage uploads.

-- =========================
-- TABLE READ ACCESS
-- =========================
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON about, project_section, projects, skills, links TO anon;

ALTER TABLE about ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE links ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'about'
          AND policyname = 'Public can read about'
    ) THEN
        CREATE POLICY "Public can read about"
            ON about
            FOR SELECT
            TO anon
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'project_section'
          AND policyname = 'Public can read project section'
    ) THEN
        CREATE POLICY "Public can read project section"
            ON project_section
            FOR SELECT
            TO anon
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'projects'
          AND policyname = 'Public can read published projects'
    ) THEN
        CREATE POLICY "Public can read published projects"
            ON projects
            FOR SELECT
            TO anon
            USING (published IS TRUE);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'skills'
          AND policyname = 'Public can read skills'
    ) THEN
        CREATE POLICY "Public can read skills"
            ON skills
            FOR SELECT
            TO anon
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'links'
          AND policyname = 'Public can read links'
    ) THEN
        CREATE POLICY "Public can read links"
            ON links
            FOR SELECT
            TO anon
            USING (true);
    END IF;
END $$;

-- =========================
-- STORAGE
-- =========================
-- Public assets are served from URL paths generated by the local admin backend.
-- Keep this bucket public for reads, but do not add anon write policies.
INSERT INTO storage.buckets (id, name, public)
VALUES ('portfolio-assets', 'portfolio-assets', true)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public;
