-- Migration 0005: credentials table.
--
-- Education and Certifications share one small persistence surface. Public
-- reads are limited to published rows; local admin writes use the service role.

CREATE TABLE IF NOT EXISTS credentials (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_kind     TEXT NOT NULL,
    title               TEXT NOT NULL DEFAULT '',
    organization        TEXT NOT NULL DEFAULT '',
    credential_type     TEXT,
    description         TEXT,
    highlights          JSONB,
    issued_label        TEXT,
    gpa                 TEXT,
    credential_url      TEXT,
    logo_url            TEXT,
    logo_key            TEXT,
    logo_scale          NUMERIC,
    published           BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order          INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT credentials_kind_check
        CHECK (credential_kind IN ('education', 'certification')),
    CONSTRAINT credentials_highlights_array_check
        CHECK (highlights IS NULL OR jsonb_typeof(highlights) = 'array')
);

COMMENT ON TABLE credentials IS
    'Education and Certification cards used by the public portfolio and local admin backend.';
COMMENT ON COLUMN credentials.credential_kind IS
    'Credential section discriminator: education or certification.';
COMMENT ON COLUMN credentials.title IS
    'Display title, such as B.S. in Computer Science or Azure Fundamentals.';
COMMENT ON COLUMN credentials.organization IS
    'Display issuer or school, such as Washington State University or Microsoft.';
COMMENT ON COLUMN credentials.credential_type IS
    'Display type, such as Bachelor''s Degree, Minor, Certification, or Certificate.';
COMMENT ON COLUMN credentials.description IS
    'Credential card body copy.';
COMMENT ON COLUMN credentials.highlights IS
    'JSON string array for credential highlight chips.';
COMMENT ON COLUMN credentials.issued_label IS
    'Display issue date, range, or expected-completion label.';
COMMENT ON COLUMN credentials.gpa IS
    'Optional display GPA, intended for education rows.';
COMMENT ON COLUMN credentials.credential_url IS
    'Optional official program, certificate, or credential URL.';
COMMENT ON COLUMN credentials.logo_url IS
    'Optional public image URL that wins over logo_key in UI-facing code.';
COMMENT ON COLUMN credentials.logo_key IS
    'Optional bundled logo key resolved by UI-facing code, such as wsu, edcc, or microsoft.';
COMMENT ON COLUMN credentials.logo_scale IS
    'Optional card logo scale; admin validation clamps this to the supported display range.';
COMMENT ON COLUMN credentials.published IS
    'Whether the credential row is available to public reads.';
COMMENT ON COLUMN credentials.sort_order IS
    'Stable ordering inside each credential_kind.';

CREATE INDEX IF NOT EXISTS credentials_public_order_idx
    ON credentials (published, credential_kind, sort_order, id);

GRANT SELECT ON credentials TO anon;

ALTER TABLE credentials ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'credentials'
          AND policyname = 'Public can read published credentials'
    ) THEN
        CREATE POLICY "Public can read published credentials"
            ON credentials
            FOR SELECT
            TO anon
            USING (published IS TRUE);
    END IF;
END $$;
