export const DEFAULT_EDUCATION = [
  {
    id: 'wsu-bs-cs',
    kind: 'education',
    title: 'B.S. in Computer Science',
    org: 'Washington State University',
    link: 'https://school.eecs.wsu.edu/academics/undergraduate-program/computer-science/',
    desc: 'Rigorous curriculum grounded in math and systems, covering software design, data structures & algorithms, programming languages, data management, and a culminating senior capstone (WSU DAS).',
    chips: ['Software Engineering', 'Algorithms', 'Data Structures', 'Databases', 'Systems & Theory'],
    issued: '2024\u20132026 \u2022 Expected in July',
    credentialType: 'Bachelor\u2019s Degree',
    gpa: '3.54',
    logoUrl: null,
    logoKey: 'wsu',
    logoScale: 0.72,
    sortOrder: 0,
  },
  {
    id: 'wsu-math-minor',
    kind: 'education',
    title: 'Minor in Mathematics',
    org: 'Washington State University',
    link: 'https://math.wsu.edu/undergraduate-studies/minors/',
    desc: 'Proof-focused foundation that strengthens analytical reasoning, abstraction, and mathematical modeling for CS problem solving.',
    chips: ['Calculus', 'Differential Equations', 'Graph Theory', 'Discrete Math', 'Linear Algebra', 'Probability & Statistics'],
    issued: '2024\u20132026',
    credentialType: 'Minor',
    gpa: '',
    logoUrl: null,
    logoKey: 'wsu',
    logoScale: 0.72,
    sortOrder: 1,
  },
  {
    id: 'edmonds-ast',
    kind: 'education',
    title: 'Associate in Science\u2013Transfer (AS-T)',
    org: 'Edmonds College',
    link: 'https://catalog.edmonds.edu/preview_program.php?catoid=53&poid=10672',
    desc: 'Transfer pathway for engineering and CS, building a strong math/physics foundation and practical programming skills for upper-division work.',
    chips: ['Computer Science', 'Physics', 'Calculus', 'Engineering'],
    issued: '2019\u20132022',
    credentialType: 'Associate Degree',
    gpa: '',
    logoUrl: null,
    logoKey: 'edcc',
    logoScale: 0.65,
    sortOrder: 2,
  },
];

export const DEFAULT_CERTIFICATIONS = [
  {
    id: 'microsoft-azure-fundamentals',
    kind: 'certification',
    title: 'Azure Fundamentals',
    org: 'Microsoft',
    link: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/',
    desc: 'Core Azure and cloud fundamentals (compute, storage, networking, identity, security, and pricing), enough to reason about cloud architectures and tradeoffs.',
    chips: ['Cloud Concepts', 'Azure Services', 'Security & Identity', 'Governance', 'Pricing & Support'],
    issued: '2025',
    credentialType: 'Certification',
    logoUrl: null,
    logoKey: 'microsoft',
    logoScale: 0.62,
    sortOrder: 0,
  },
  {
    id: 'edmonds-c-cpp-developer',
    kind: 'certification',
    title: 'C/C++ Developer',
    org: 'Edmonds College',
    link: 'https://catalog.edmonds.edu/preview_program.php?catoid=63&poid=15850',
    desc: 'C/C++ core sequence covering procedural fundamentals, object-oriented design, algorithm efficiency, and core data structures using the C++ Standard Library.',
    chips: ['C/C++', 'Pointers & Recursion', 'Object-Oriented', 'Data Structures', 'Complexity (Big-O)'],
    issued: '2022',
    credentialType: 'Certificate',
    logoUrl: null,
    logoKey: 'edcc',
    logoScale: 0.65,
    sortOrder: 1,
  },
];

export const DEFAULT_CREDENTIALS = {
  education: DEFAULT_EDUCATION,
  certifications: DEFAULT_CERTIFICATIONS,
};
