export const PROJECT_AGENT_SOURCE_PDF_MAX_BYTES = 10 * 1024 * 1024;
export const PROJECT_AGENT_SOURCE_PDF_MAX_PAGES = 40;
export const PROJECT_AGENT_SOURCE_PDF_MAX_TEXT_LENGTH = 80000;

export const PROJECT_AGENT_SOURCE_ZIP_MAX_BYTES = 20 * 1024 * 1024;
export const PROJECT_AGENT_SOURCE_ZIP_MAX_ENTRIES = 200;
export const PROJECT_AGENT_SOURCE_ZIP_MAX_INCLUDED_FILES = 10;
export const PROJECT_AGENT_SOURCE_ZIP_ENTRY_MAX_BYTES = 512 * 1024;
export const PROJECT_AGENT_SOURCE_ZIP_TOTAL_EXTRACTED_BYTES = 5 * 1024 * 1024;
