export const PROJECT_AGENT_SOURCE_ALLOWED_EXTENSIONS = [
  '.txt',
  '.text',
  '.md',
  '.markdown',
  '.mdx',
  '.rst',
  '.adoc',
  '.json',
  '.jsonc',
  '.json5',
  '.csv',
  '.tsv',
  '.ndjson',
  '.log',
  '.html',
  '.htm',
  '.css',
  '.scss',
  '.sass',
  '.less',
  '.js',
  '.mjs',
  '.cjs',
  '.jsx',
  '.ts',
  '.mts',
  '.cts',
  '.tsx',
  '.py',
  '.pyw',
  '.java',
  '.c',
  '.cc',
  '.cpp',
  '.cxx',
  '.h',
  '.hh',
  '.hpp',
  '.hxx',
  '.cs',
  '.go',
  '.rs',
  '.rb',
  '.php',
  '.swift',
  '.kt',
  '.kts',
  '.r',
  '.dart',
  '.scala',
  '.sc',
  '.lua',
  '.ex',
  '.exs',
  '.erl',
  '.hrl',
  '.clj',
  '.cljs',
  '.cljc',
  '.fs',
  '.fsx',
  '.fsi',
  '.vb',
  '.svelte',
  '.vue',
  '.astro',
  '.graphql',
  '.gql',
  '.proto',
  '.prisma',
  '.sql',
  '.yaml',
  '.yml',
  '.toml',
  '.xml',
  '.ini',
  '.cfg',
  '.conf',
  '.properties',
  '.editorconfig',
  '.dockerfile',
  '.sh',
  '.bash',
  '.zsh',
  '.fish',
  '.ps1',
  '.bat',
  '.cmd',
  '.tf',
  '.tfvars',
  '.hcl',
  '.gradle',
  '.groovy',
  '.sln',
  '.csproj',
  '.fsproj',
  '.vbproj',
  '.ipynb',
];

export const PROJECT_AGENT_SOURCE_ALLOWED_FILENAMES = [
  'Dockerfile',
  'Makefile',
  'Procfile',
  'LICENSE',
  'README',
  '.gitignore',
  '.dockerignore',
  '.editorconfig',
  '.env.example',
];

export const PROJECT_AGENT_TEXT_SOURCE_MEDIA_TYPES_BY_EXTENSION = new Map([
  ['.txt', 'text/plain'],
  ['.text', 'text/plain'],
  ['.md', 'text/markdown'],
  ['.markdown', 'text/markdown'],
  ['.mdx', 'text/markdown'],
  ['.rst', 'text/plain'],
  ['.adoc', 'text/plain'],
  ['.json', 'application/json'],
  ['.jsonc', 'application/json'],
  ['.json5', 'application/json'],
  ['.csv', 'text/csv'],
  ['.tsv', 'text/tab-separated-values'],
  ['.ndjson', 'application/x-ndjson'],
  ['.log', 'text/plain'],
  ['.html', 'text/html'],
  ['.htm', 'text/html'],
  ['.css', 'text/css'],
  ['.scss', 'text/x-scss'],
  ['.sass', 'text/x-sass'],
  ['.less', 'text/less'],
  ['.js', 'text/javascript'],
  ['.mjs', 'text/javascript'],
  ['.cjs', 'text/javascript'],
  ['.jsx', 'text/javascript'],
  ['.ts', 'text/typescript'],
  ['.mts', 'text/typescript'],
  ['.cts', 'text/typescript'],
  ['.tsx', 'text/typescript'],
  ['.py', 'text/x-python'],
  ['.pyw', 'text/x-python'],
  ['.java', 'text/x-java-source'],
  ['.c', 'text/x-c'],
  ['.cc', 'text/x-c++src'],
  ['.cpp', 'text/x-c++src'],
  ['.cxx', 'text/x-c++src'],
  ['.h', 'text/x-c'],
  ['.hh', 'text/x-c++hdr'],
  ['.hpp', 'text/x-c++hdr'],
  ['.hxx', 'text/x-c++hdr'],
  ['.cs', 'text/x-csharp'],
  ['.go', 'text/x-go'],
  ['.rs', 'text/rust'],
  ['.rb', 'text/x-ruby'],
  ['.php', 'text/x-php'],
  ['.swift', 'text/x-swift'],
  ['.kt', 'text/x-kotlin'],
  ['.kts', 'text/x-kotlin'],
  ['.r', 'text/x-r'],
  ['.dart', 'text/x-dart'],
  ['.scala', 'text/x-scala'],
  ['.sc', 'text/x-scala'],
  ['.lua', 'text/x-lua'],
  ['.ex', 'text/x-elixir'],
  ['.exs', 'text/x-elixir'],
  ['.erl', 'text/x-erlang'],
  ['.hrl', 'text/x-erlang'],
  ['.clj', 'text/x-clojure'],
  ['.cljs', 'text/x-clojure'],
  ['.cljc', 'text/x-clojure'],
  ['.fs', 'text/x-fsharp'],
  ['.fsx', 'text/x-fsharp'],
  ['.fsi', 'text/x-fsharp'],
  ['.vb', 'text/x-vb'],
  ['.svelte', 'text/html'],
  ['.vue', 'text/html'],
  ['.astro', 'text/html'],
  ['.graphql', 'application/graphql'],
  ['.gql', 'application/graphql'],
  ['.proto', 'text/x-protobuf'],
  ['.prisma', 'text/plain'],
  ['.sql', 'application/sql'],
  ['.yaml', 'application/yaml'],
  ['.yml', 'application/yaml'],
  ['.toml', 'application/toml'],
  ['.xml', 'application/xml'],
  ['.ini', 'text/plain'],
  ['.cfg', 'text/plain'],
  ['.conf', 'text/plain'],
  ['.properties', 'text/plain'],
  ['.editorconfig', 'text/plain'],
  ['.dockerfile', 'text/plain'],
  ['.sh', 'application/x-sh'],
  ['.bash', 'application/x-sh'],
  ['.zsh', 'application/x-sh'],
  ['.fish', 'application/x-sh'],
  ['.ps1', 'text/plain'],
  ['.bat', 'text/plain'],
  ['.cmd', 'text/plain'],
  ['.tf', 'text/plain'],
  ['.tfvars', 'text/plain'],
  ['.hcl', 'text/plain'],
  ['.gradle', 'text/plain'],
  ['.groovy', 'text/x-groovy'],
  ['.sln', 'text/plain'],
  ['.csproj', 'application/xml'],
  ['.fsproj', 'application/xml'],
  ['.vbproj', 'application/xml'],
  ['.ipynb', 'application/x-ipynb+json'],
]);

export const TEXT_SOURCE_ALLOWED_EXTENSION_SET = new Set(PROJECT_AGENT_SOURCE_ALLOWED_EXTENSIONS);
export const TEXT_SOURCE_ALLOWED_FILENAME_SET = new Set(
  PROJECT_AGENT_SOURCE_ALLOWED_FILENAMES.map((name) => name.toLowerCase()),
);
export const TEXT_SOURCE_DISALLOWED_SECRET_FILENAMES = new Set([
  '.env',
  '.npmrc',
  '.pypirc',
  '.netrc',
  '.pgpass',
  '.dockercfg',
  'id_rsa',
  'id_dsa',
  'id_ecdsa',
  'id_ed25519',
]);
export const TEXT_SOURCE_DISALLOWED_SECRET_EXTENSIONS = new Set([
  '.pem',
  '.key',
  '.p12',
  '.pfx',
  '.crt',
  '.cer',
  '.der',
  '.jks',
  '.keystore',
]);
export const TEXT_SOURCE_DISALLOWED_BINARY_OR_DUMP_EXTENSIONS = new Set([
  '.db',
  '.sqlite',
  '.sqlite3',
  '.dump',
]);
export const TEXT_SOURCE_GENERATED_SOURCE_PATTERN = /(?:^|[._-])generated\.[a-z0-9]+$/i;
export const TEXT_SOURCE_GENERATED_BUNDLE_PATTERN = /(?:^|[._-])(?:bundle|min)\.(?:cjs|css|js|mjs)$/i;
